# Generated by Django 5.2.8 on 2026-04-17 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_assignmentmarks_mcqmarks_quizmarks_studentenrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
